name: manage_content
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  archive: ^3.3.5
  collection: ^1.16.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
